## Lab - Matrices - David Gitonga

In [1]:
import numpy as np

A = np.array([[10, 95, 8],
     [95, 20, 9],
     [8, 9, 30]])

print(np.transpose(A))

[[10 95  8]
 [95 20  9]
 [ 8  9 30]]


In [2]:
B = np.array([[5, 8, 3, 6],
    [95, 20, 9, 3],
    [8, 9, 30, 3],
    [8, 9, 30, 3]])

print(np.transpose(B))

[[ 5 95  8  8]
 [ 8 20  9  9]
 [ 3  9 30 30]
 [ 6  3  3  3]]


In [3]:
C = np.array([[0, 6, 250],
    [-6, 0, 86.3],
    [-250, -86.3, 0]])

print(np.transpose(C))

[[   0.    -6.  -250. ]
 [   6.     0.   -86.3]
 [ 250.    86.3    0. ]]


In [4]:


def inverse_matrix(matrix):
    x = np.array(matrix)
    
    # print original matrix
    print('Original matrix')
    print(x)
    
    # print original matrix
    print('\nInverse matrix')
    print(np.linalg.inv(x))
    print('\n')

inverse_matrix(A)
inverse_matrix(B)
inverse_matrix(C)

Original matrix
[[10 95  8]
 [95 20  9]
 [ 8  9 30]]

Inverse matrix
[[-0.00205009  0.0109733  -0.0027453 ]
 [ 0.0109733  -0.00093222 -0.00264655]
 [-0.0027453  -0.00264655  0.03485938]]


Original matrix
[[ 5  8  3  6]
 [95 20  9  3]
 [ 8  9 30  3]
 [ 8  9 30  3]]

Inverse matrix


LinAlgError: Singular matrix

Matrix B & C above have a determinant of zero. This is the definition of a Singular matrix (one for which an inverse does not exist)<br>

A is a 3x3 matrice<br>
B is a 4x4 matrice<br>
C is a 3x3 matrice

In [ ]:
def add_matrices(A, B):
    # iterate through rows
    for i in range(len(A)):
       # iterate through columns
       for j in range(len(A[0])):
           result[i][j] = A[i][j] + B[i][j]

    for r in result:
       print(r)
    
add_matrices(A, B)

In [ ]:
def multiply_matrices(A, B):
    # iterate through rows of X
    for i in range(len(A)):
       # iterate through columns of Y
       for j in range(len(B[0])):
           # iterate through rows of Y
           for k in range(len(B)):
               result[i][j] += A[i][k] * B[k][j]

    for r in result:
       print(r)
    
multiply_matrices(A, B)