In [2]:
import numpy as np

A = np.array([1,4])
B = np.array([[1,3],[1,2]])

In [3]:
np.matmul(B,A)

array([13,  9])

In [4]:
np.matmul(A,B)

array([ 5, 11])

In [5]:
print(A)

[1 4]


In [6]:
print(B)

[[1 3]
 [1 2]]


In [10]:
A = np.array([1,4]).T
B = np.array([[1,3],[1,2]])

In [11]:
np.matmul(B,A)

array([13,  9])

In [12]:
np.matmul(A,B)

array([ 5, 11])

In [27]:
A = np.array([[8,15,30],[43, 2, 9],[11, 25, 62]])
A_inv = np.linalg.inv(A)
print(A)
print(A_inv)

[[ 8 15 30]
 [43  2  9]
 [11 25 62]]
[[ 0.01307782  0.02330701 -0.00971125]
 [ 0.33238379 -0.02149424 -0.15771073]
 [-0.13634598  0.00453192  0.08144503]]


In [24]:
D = np.matmul(A, A_inv)
print(D)

[[1.00000000e+00 6.93889390e-18 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 3.46944695e-18 1.00000000e+00]]


In [25]:
type(D[0,1])

numpy.float64